import docx

doc = docx.Document()

doc.add_heading('Πληροφορίες Πτυχιακής Εργασίας / Thesis Information', 0)

doc.add_heading('Τίτλος (Ελληνικά)', level=1)
doc.add_paragraph('ΣΧΕΔΙΑΣΗ ΚΑΙ ΥΛΟΠΟΙΗΣΗ ΕΦΑΡΜΟΓΗΣ ΔΙΑΧΕΙΡΙΣΗΣ ΠΑΡΑΓΓΕΛΙΩΝ ΥΨΗΛΟΥ ΡΥΘΜΟΥ ΓΙΑ ΕΚΔΗΛΩΣΕΙΣ ΜΕ ΜΕΓΑΛΟ ΠΛΗΘΟΣ ΣΥΜΜΕΤΕΧΟΝΤΩΝ')

doc.add_heading('Title (English)', level=1)
doc.add_paragraph('DESIGN AND IMPLEMENTATION OF A HIGH-THROUGHPUT ORDER MANAGEMENT APPLICATION FOR LARGE-SCALE EVENTS')

doc.add_heading('Στοιχεία Φοιτητή / Student Details', level=1)
doc.add_paragraph('Πετράκης Γεώργιος (Petrakis Georgios)')
doc.add_paragraph('Αριθμός Μητρώου (Registration Number): 2814')

doc.add_heading('Στοιχεία Επιτροπής / Committee Details', level=1)
doc.add_paragraph('Μαργαρίτη Σπυριδούλα, Εργαστηριακό Διδακτικό Προσωπικό (Ε.ΔΙ.Π.), Τμήμα Πληροφορικής και Τηλεπικοινωνιών, Πανεπιστήμιο Ιωαννίνων (Επιβλέπουσα / Supervisor)')
doc.add_paragraph('Γκόγκος Χρήστος, Καθηγητής, Τμήμα Πληροφορικής και Τηλεπικοινωνιών, Πανεπιστήμιο Ιωαννίνων (Επιβλέπων / Supervisor)')
doc.add_paragraph('Λιάγκου Βασιλική, Επίκουρη Καθηγήτρια, Τμήμα Πληροφορικής και Τηλεπικοινωνιών, Πανεπιστήμιο Ιωαννίνων / Vasiliki Liagkou, Assistant Professor (Μέλος / Member)')

doc.add_heading('Περίληψη (Ελληνικά)', level=1)
doc.add_paragraph('Η ικανότητα παροχής αδιάλειπτης συνδεσιμότητας και χρήσης αρχιτεκτονικής "cloud-first" (με προτεραιότητα στο cloud) για τα Συστήματα Διαχείρισης Παραγγελιών και τον κλάδο των Εκδηλώσεων έχει γίνει κύριο σημείο εστίασης της ψηφιακής ανατροπής (digital disruption) και στους δύο αυτούς τομείς. Ωστόσο, λόγω της φύσης των προσωρινών τους εκδηλώσεων (π.χ. Πολιτιστικά Φεστιβάλ) και των σχετικών ad-hoc υποδομών δικτύου, τα περιβάλλοντα αυτά θεωρούνται εξαιρετικά εχθρικά. Αυτό οφείλεται σε μεγάλο βαθμό σε ακραίες εξάρσεις καθυστέρησης (latency spikes), σε τοπικές Παρεμβολές Ραδιοσυχνοτήτων (RFI) και στην πλήρη απώλεια συνδεσιμότητας. Ως εκ τούτου, σε περιβάλλοντα όπου υπάρχουν πολυάριθμα σημεία υψηλού φόρτου (π.χ. τερματικά POS, Κιόσκια, κ.λπ.), η χρήση της Σύγχρονης Περιοδικής Ερώτησης HTTP (Synchronous HTTP Polling) στα Παραδοσιακά Συστήματα Σημείων Πώλησης (POS) συχνά προκαλεί προβλήματα που αναφέρονται ως το "Πρόβλημα των Δύο Στρατηγών", το οποίο οδηγεί σε ακραίο Αποσυγχρονισμό Δεδομένων, Παραγγελίες-Φαντάσματα και Οικονομικές Ασυμφωνίες.')
doc.add_paragraph('Αυτή η πτυχιακή εργασία περιγράφει τον σχεδιασμό, την ανάπτυξη και την πειραματική επικύρωση ενός Συστήματος Διαχείρισης Παραγγελιών (OMS) που παρέχει ικανότητα υψηλής απόδοσης για τη διαχείριση παραγγελιών σε ένα τοπικό περιβάλλον. Το OMS είναι ειδικά σχεδιασμένο ώστε να είναι ικανό να διαχειρίζεται παραγγελίες σε εχθρικά περιβάλλοντα δικτύωσης. Ένα σημαντικό αρχιτεκτονικό στοιχείο αυτού του συστήματος χρησιμοποιεί μια Βελτιστοποιημένη, Καθοδηγούμενη από Γεγονότα (Event-Driven) Εσωτερική Τοπολογία, κατασκευασμένη πάνω στη στοίβα τεχνολογιών MERN (MongoDB, Express.js, React, Node.js). Ένα σημαντικό πλεονέκτημα της χρήσης αυτού του τύπου εσωτερικής τοπολογίας είναι ότι επιτρέπει την αποσύνδεση της Επιχειρησιακής Διεπαφής από τις Εξωτερικές Εξαρτήσεις του Cloud. Για να βελτιώσει περαιτέρω τις δυνατότητες απόδοσής της σε εχθρικά περιβάλλοντα δικτύωσης, η Προτεινόμενη Αρχιτεκτονική αντικαθιστά το Synchronous HTTP Polling με Αμφίδρομες (Full-Duplex) Συνδέσεις WebSocket και χρησιμοποιεί Ανθεκτικές Διεπαφές Virtual DOM βασισμένες σε React καθώς και Προσωρινή Αποθήκευση Offline-First (με προτεραιότητα στην εκτός σύνδεσης λειτουργία). Αυτό γίνεται για να εξασφαλιστεί ο Ντετερμινιστικός Συγχρονισμός Κατάστασης σε Απομονωμένους Επιχειρησιακούς Κόμβους (Ταμίες, Προσωπικό Κουζίνας, Διοικητικά Κέντρα). Επιπλέον, χρησιμοποιούνται και επιβάλλονται αυστηρά όρια ασφαλείας με τη χρήση JWTs και RBAC Μηδενικής Εμπιστοσύνης (Zero Trust) για τον Έλεγχο Πρόσβασης.')
doc.add_paragraph('Προκειμένου να αξιολογηθούν εμπειρικά τα χαρακτηριστικά απόδοσης της προτεινόμενης αρχιτεκτονικής, πραγματοποιήθηκαν αυστηρές αξιολογήσεις. Αυτές οι αξιολογήσεις περιλάμβαναν Δοκιμές Ακραίας Καταπόνησης (Stress Testing) Υψηλής Έντασης (Επικυρωμένη Σταθερότητα σε 1,58 Εκατομμύρια Ταυτόχρονες Συναλλαγές) και Προσομοιώσεις Μηχανικής Χάους (Chaos Engineering) που κατέδειξαν Στόχο Χρόνου Ανάκαμψης (RTO) από Σοβαρή Βλάβη στα 310 Χιλιοστά του δευτερολέπτου. Οι εργαστηριακές μετρήσεις που έγιναν κατά τη διάρκεια των αξιολογήσεων επικυρώθηκαν στη συνέχεια μέσω εκτεταμένων εφαρμογών σε πραγματικές συνθήκες (field deployments) κατά τη διάρκεια επτά ημερών με μαζικές ριπές κίνησης δεδομένων (Burst Traffic). Η τηλεμετρία που συλλέχθηκε κατά τη διάρκεια της εφαρμογής σε πραγματικές συνθήκες επικύρωσε ότι οι Ασύγχρονες Αρχιτεκτονικές Βρόχου Γεγονότων (Event Loop) μειώνουν σημαντικά τον φόρτο δεδομένων δικτύου (Bandwidth Payload) και εξαλείφουν την Υποβάθμιση Βάσει Σύνδεσης (Connection-Based Degradation) όταν εφαρμόζονται σε Εχθρικά Περιβάλλοντα Δικτύωσης.')
doc.add_paragraph('Λέξεις Κλειδιά: Σύστημα Διαχείρισης Παραγγελιών, Αρχιτεκτονική Καθοδηγούμενη από Γεγονότα, WebSockets, Μοντέλο Εκτέλεσης σε Τοπικό Επίπεδο (Local-First Topology), Δίκτυα Ad-hoc, Επεξεργασία Υψηλού Ρυθμού, Συγχρονισμός Πραγματικού Χρόνου.')

doc.add_heading('Abstract (English)', level=1)
doc.add_paragraph('The ability to provide uninterrupted connectivity and employ "cloud-first" architecture for the Order Management System and Event Industries has become a major focus of digital disruption in both of these spaces. However, due to the nature of their temporary events (i.e., Cultural Festivals) and associated ad-hoc network infrastructures, they are considered extremely hostile. This is largely due to extreme latency spikes, localized Radio Frequency Interference (RFI), and complete loss of connectivity. As such, in environments where there are numerous intensity points (e.g., POS terminals, Kiosks, etc.) and the use of Synchronous HTTP Polling in Traditional Point-of-Sale (POS) Systems will often cause problems referred to as the "Two Generals Problem" which results in extreme Data Desynchronization, Phantom Orders and Financial Discrepancies.')
doc.add_paragraph('This dissertation describes the design, development and experimental validation of an Order Management System (OMS) that provides a high-performance capability for managing orders in a localized environment. The OMS is specifically designed to be capable of managing orders in hostile networking environments. An important architectural component of this system utilizes an Optimized, Event Driven Internal Topology built upon the MERN technology stack (MongoDB, Express.js, React, Node.js). A significant benefit of utilizing this type of internal topology is that it allows for a decoupling of the Operational Interface from External Cloud Dependencies. To further improve its performance capabilities in hostile networking environments, the Proposed Architecture replaces Synchronous HTTP Polling with Full-Duplex WebSocket Connections and uses Resilient React Based Virtual DOM Interfaces and Offline-First Caching to ensure Deterministic State Synchronization Across Isolated Operational Nodes (Cashiers, Kitchen Staff, Administrative Hubs). Additionally, strict security boundaries are utilized and enforced using JWTs and Zero Trust RBAC for Access Control.')
doc.add_paragraph('In order to empirically evaluate the performance characteristics of the proposed architecture, rigorous evaluations were performed. These evaluations included High-Intensity Stress Testing (Validated Stability at 1.58 Million Concurrent Transactions) and Chaos Engineering Simulations that demonstrated a Severe Failure Recovery Time Objective (RTO) of 310 Milliseconds. Laboratory measurements made during the evaluations were subsequently validated through extensive field deployments over the course of seven days with massive Burst Traffic. Telemetry collected during the field deployment validated that Asynchronous Event Loop Architectures significantly reduce Bandwidth Payload and eliminate Connection-Based Degradation when deployed in Hostile Networking Environments.')
doc.add_paragraph('Keywords: Order Management System, Event-Driven Architecture, WebSockets, Local-First Topology, Ad-hoc Networks, High-Throughput Computing, Real-Time Synchronization.')

doc.save('Thesis_Library_Submission.docx')
print('Document saved successfully as Thesis_Library_Submission.docx')
